#pragma once

// Auto-generated by tools/famitracker_to_song_atlas.py
// SONGS_ATLAS_META: {"type":"songs_atlas_v1","settings":{"channel":0,"row_ms":38,"hold_empty":true,"bpm":150.0,"rows_per_beat":4.0},"songs":[{"name":"manny","source":"MANNY.txt","input":"../tools/MANNY.txt"}]}

struct SongDef
{
  const char *name;
  const float *notes;
  const unsigned short *durMs;
  int len;
};

static const float mannyNotes[] = {196.00f, 146.83f, 196.00f, 146.83f, 196.00f, 146.83f, 196.00f, 246.94f, 293.66f, 261.63f, 220.00f, 261.63f, 220.00f, 261.63f, 220.00f, 185.00f, 220.00f, 146.83f};
static const unsigned short mannyDurMs[] = {228, 76, 228, 76, 76, 76, 76, 76, 304, 228, 76, 228, 76, 76, 76, 76, 76, 304};
static const int mannyLen = sizeof(mannyNotes) / sizeof(mannyNotes[0]);

const SongDef songs[] = {
  {"manny", mannyNotes, mannyDurMs, mannyLen},
};
const int songsCount = sizeof(songs) / sizeof(songs[0]);
