#pragma once

// Auto-generated by tools/famitracker_to_song_atlas.py
// SONGS_ATLAS_META: {"type":"songs_atlas_v1","settings":{"channel":2,"row_ms":38,"hold_empty":true,"bpm":150.0,"rows_per_beat":4.0},"songs":[{"name":"stars","source":"stars.txt","input":"../tools/stars.txt"}]}

struct SongDef
{
  const char *name;
  const float *notes;
  const unsigned short *durMs;
  int len;
};

static const float starsNotes[] = {130.81f, 196.00f, 220.00f, 196.00f, 174.61f, 164.81f, 146.83f, 130.81f};
static const unsigned short starsDurMs[] = {304, 304, 304, 304, 304, 304, 304, 304};
static const int starsLen = sizeof(starsNotes) / sizeof(starsNotes[0]);

const SongDef songs[] = {
  {"stars", starsNotes, starsDurMs, starsLen},
};
const int songsCount = sizeof(songs) / sizeof(songs[0]);
