#pragma once

// Auto-generated by tools/famitracker_to_song_atlas.py
// SONGS_ATLAS_META: {"type":"songs_atlas_v1","settings":{"channel":0,"row_ms":null,"ft_timing":true,"mix_4ch":false,"mix_channels":[],"export_4ch":true,"channels_4ch":[0,1,2,3],"hold_empty":false,"bpm":150.0,"rows_per_beat":4.0},"songs":[{"name":"stars","source":"stars.txt","input":"../tools/stars.txt","row_ms":83}]}

struct SongDef
{
  const char *name;
  const float *notes;
  const unsigned short *durMs;
  int len;
};

#define SONGS_HAS_4CH 1
struct SongChannelsDef
{
  const float *notes[4];
  const unsigned short *durMs[4];
  int len[4];
  unsigned char wave[4];
  unsigned char channelCount;
};

static const float starsNotes[] = {130.81f, 0.0f, 130.81f, 0.0f, 196.00f, 0.0f, 196.00f, 0.0f, 220.00f, 0.0f, 220.00f, 0.0f, 196.00f, 0.0f, 174.61f, 0.0f, 174.61f, 0.0f, 164.81f, 0.0f, 164.81f, 0.0f, 146.83f, 0.0f, 146.83f, 0.0f, 130.81f, 0.0f};
static const unsigned short starsDurMs[] = {83, 249, 83, 249, 83, 249, 83, 249, 83, 249, 83, 249, 83, 581, 83, 249, 83, 249, 83, 249, 83, 249, 83, 249, 83, 249, 83, 581};
static const int starsLen = sizeof(starsNotes) / sizeof(starsNotes[0]);
static const float starsCh0Notes[] = {130.81f, 0.0f, 130.81f, 0.0f, 196.00f, 0.0f, 196.00f, 0.0f, 220.00f, 0.0f, 220.00f, 0.0f, 196.00f, 0.0f, 174.61f, 0.0f, 174.61f, 0.0f, 164.81f, 0.0f, 164.81f, 0.0f, 146.83f, 0.0f, 146.83f, 0.0f, 130.81f, 0.0f};
static const unsigned short starsCh0DurMs[] = {83, 249, 83, 249, 83, 249, 83, 249, 83, 249, 83, 249, 83, 581, 83, 249, 83, 249, 83, 249, 83, 249, 83, 249, 83, 249, 83, 581};
static const int starsCh0Len = sizeof(starsCh0Notes) / sizeof(starsCh0Notes[0]);
static const float starsCh1Notes[] = {0.0f, 261.63f, 0.0f, 261.63f, 0.0f, 392.00f, 0.0f, 392.00f, 0.0f, 440.00f, 0.0f, 440.00f, 0.0f, 392.00f, 0.0f, 349.23f, 0.0f, 349.23f, 0.0f, 329.63f, 0.0f, 329.63f, 0.0f, 293.66f, 0.0f, 293.66f, 0.0f, 261.63f, 0.0f};
static const unsigned short starsCh1DurMs[] = {83, 83, 249, 83, 249, 83, 249, 83, 249, 83, 166, 83, 332, 83, 581, 83, 249, 83, 249, 83, 249, 83, 249, 83, 249, 83, 249, 83, 498};
static const int starsCh1Len = sizeof(starsCh1Notes) / sizeof(starsCh1Notes[0]);
static const float starsCh2Notes[] = {130.81f, 0.0f, 130.81f, 0.0f, 196.00f, 0.0f, 196.00f, 0.0f, 220.00f, 0.0f, 220.00f, 0.0f, 196.00f, 0.0f, 174.61f, 0.0f, 174.61f, 0.0f, 164.81f, 0.0f, 164.81f, 0.0f, 146.83f, 0.0f, 146.83f, 0.0f, 130.81f, 0.0f};
static const unsigned short starsCh2DurMs[] = {83, 249, 83, 249, 83, 249, 83, 249, 83, 249, 83, 249, 83, 581, 83, 249, 83, 249, 83, 249, 83, 249, 83, 249, 83, 249, 83, 581};
static const int starsCh2Len = sizeof(starsCh2Notes) / sizeof(starsCh2Notes[0]);
static const float starsCh3Notes[] = {176.00f, 0.0f, 232.00f, 0.0f, 176.00f, 0.0f, 232.00f, 0.0f, 176.00f, 0.0f, 232.00f, 0.0f, 176.00f, 0.0f, 232.00f, 0.0f, 176.00f, 0.0f, 232.00f, 0.0f, 176.00f, 0.0f, 232.00f, 0.0f, 176.00f, 0.0f, 232.00f, 0.0f, 176.00f, 0.0f, 176.00f, 0.0f, 176.00f, 0.0f, 232.00f, 0.0f, 176.00f, 0.0f, 232.00f, 0.0f, 176.00f, 0.0f, 232.00f, 0.0f, 176.00f, 0.0f, 232.00f, 0.0f, 176.00f, 0.0f, 232.00f, 0.0f, 176.00f, 0.0f, 232.00f, 0.0f, 176.00f, 0.0f, 232.00f, 0.0f, 232.00f, 0.0f, 232.00f, 0.0f};
static const unsigned short starsCh3DurMs[] = {83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83, 83};
static const int starsCh3Len = sizeof(starsCh3Notes) / sizeof(starsCh3Notes[0]);

const SongDef songs[] = {
  {"stars", starsNotes, starsDurMs, starsLen},
};
const int songsCount = sizeof(songs) / sizeof(songs[0]);

const SongChannelsDef songsCh[] = {
  {{{starsCh0Notes, starsCh1Notes, starsCh2Notes, starsCh3Notes}, {starsCh0DurMs, starsCh1DurMs, starsCh2DurMs, starsCh3DurMs}, {starsCh0Len, starsCh1Len, starsCh2Len, starsCh3Len}, {0, 1, 2, 3}, 4}},
};
