#pragma once

// Auto-generated by tools/famitracker_to_song_atlas.py
// SONGS_ATLAS_META: {"type":"songs_atlas_v1","settings":{"channel":0,"row_ms":90,"hold_empty":false,"bpm":166.0,"rows_per_beat":4.0},"songs":[{"name":"manny","source":"MANNY.txt","input":"../tools/MANNY.txt"},{"name":"stars","source":"stars.txt","input":"../tools/stars.txt"}]}

struct SongDef
{
  const char *name;
  const float *notes;
  const unsigned short *durMs;
  int len;
};

static const float mannyNotes[] = {196.00f, 0.0f, 146.83f, 0.0f, 196.00f, 0.0f, 146.83f, 0.0f, 196.00f, 0.0f, 146.83f, 0.0f, 196.00f, 0.0f, 246.94f, 0.0f, 293.66f, 0.0f, 261.63f, 0.0f, 220.00f, 0.0f, 261.63f, 0.0f, 220.00f, 0.0f, 261.63f, 0.0f, 220.00f, 0.0f, 185.00f, 0.0f, 220.00f, 0.0f, 146.83f, 0.0f};
static const unsigned short mannyDurMs[] = {90, 450, 90, 90, 90, 450, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 630, 90, 450, 90, 90, 90, 450, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 630};
static const int mannyLen = sizeof(mannyNotes) / sizeof(mannyNotes[0]);

static const float starsNotes[] = {130.81f, 0.0f, 130.81f, 0.0f, 196.00f, 0.0f, 196.00f, 0.0f, 220.00f, 0.0f, 220.00f, 0.0f, 196.00f, 0.0f, 174.61f, 0.0f, 174.61f, 0.0f, 164.81f, 0.0f, 164.81f, 0.0f, 146.83f, 0.0f, 146.83f, 0.0f, 130.81f, 0.0f};
static const unsigned short starsDurMs[] = {90, 270, 90, 270, 90, 270, 90, 270, 90, 270, 90, 270, 90, 630, 90, 270, 90, 270, 90, 270, 90, 270, 90, 270, 90, 270, 90, 630};
static const int starsLen = sizeof(starsNotes) / sizeof(starsNotes[0]);

const SongDef songs[] = {
  {"manny", mannyNotes, mannyDurMs, mannyLen},
  {"stars", starsNotes, starsDurMs, starsLen},
};
const int songsCount = sizeof(songs) / sizeof(songs[0]);
